# Settings
baseurl: /class-boilerplate
permalink: pretty

# About
title: Class boilerplate
tagline: A Jekyll template for LMS
authors:
  - name: Luca De Feo
    url: 'http://defeo.lu'
created: 2014
license:
  name: MIT license
  shortname: MIT license
  url: /LICENSE
  
# Collections
collections:
  addons:
    output: true

kramdown:
  parse_block_html: true
